<?php

/**
 * ENVIRONMENT BASE URLS's
 */
define('ENVIRONMENT_TIGO_SANDBOX','');
define('ENVIRONMENT_TIGO_LIVE','');
define('ENVIRONMENT_WAZO_LIVE','');
define('ENVIRONMENT_ONE_SIGNAL','');

/**
 * MERCHANT ACCOUNT DETAILS
 */
define('TIGO_MERCHANT_ACCOUNT_NAME','');
define('TIGO_MERCHANT_ACCOUNT_MSISDN','');
define('TIGO_MERCHANT_ACCOUNT_SECRET','');
define('TIGO_MERCHANT_ACCOUNT_KEY','');
define('TIGO_MERCHANT_ACCOUNT_PIN','');
define('WAZO_MERCHANT_ID','');
define('WAZO_MERCHANT_GRANT_TYPE','');
define('WAZO_MERCHANT_SCOPE','');
define('WAZO_MERCHANT_SECRET','');
define('WAZO_OPERATOR_NAME','');
define('STRIPE_SECRET_API_KEY','');

/**
 * TRANSACTION DETAILS
 */
define('TRANSACTION_COUNTRY_NAME','TZA');
define('TRANSACTION_COUNTRY_CODE','255');
define('TRANSACTION_COUNTRY_CURRENCY','TZS');
define('TRANSACTION_LANGUAGE','SWAHILI');
define('TRANSACTION_LANGUAGE_WAZO','SWA');
define('TRANSACTION_SUCCESS','200');
define('TRANSACTION_FAILURE','404');
define('TRANSACTION_URL_CALLBACK','');
define('TRANSACTION_URL_REDIRECTION','');
